#!/usr/bin/env node
// Rebuild db/control.sql and db/tenant.sql (the "fresh database" schemas that
// a new CONTROL and every new school are loaded from) by applying all
// migrations to empty SQLite databases and dumping the result, and
// src/services/tenant_migrations.ts, which provisioning records as applied.
//
//   node scripts/schema-sync.mjs           write the files
//   node scripts/schema-sync.mjs --check   exit 1 if any is out of date (CI)
//   --out <dir>                            write there instead (tests)
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { WORKER, buildFresh, dump, listMigrations, pad } from './migrate-lib.mjs'

const args = process.argv.slice(2)
const check = args.includes('--check')
const outIdx = args.indexOf('--out')
const outDir = outIdx >= 0 ? args[outIdx + 1] : null

export async function generate() {
  const files = {}
  for (const scope of ['control', 'tenant']) {
    const { target, since } = await buildFresh(scope)
    const last = listMigrations(scope).at(-1)
    const header = `-- GENERATED by scripts/schema-sync.mjs from migrations/${scope}/ (through ${pad(last.version)}_${last.name}).
-- Do not edit: write a migration (npm run migrate -- new ${scope} <name>), then npm run schema:sync.
-- ${scope === 'control' ? 'A fresh CONTROL database.' : 'A fresh school database; provisioning (src/services/provision.ts) loads it.'}
`
    files[`db/${scope}.sql`] = dump(target.db, { header, since })
    target.close()
  }
  const list = listMigrations('tenant').map((m) => `  { version: ${m.version}, name: '${m.name}', checksum: '${m.checksum}' },`).join('\n')
  files['src/services/tenant_migrations.ts'] = `// GENERATED by scripts/schema-sync.mjs. Do not edit.
// Every tenant migration db/tenant.sql already contains; provisioning records
// them in a new school's _migrations so the runner never re-applies them.
export const TENANT_MIGRATIONS: ReadonlyArray<{ version: number; name: string; checksum: string }> = [
${list}
]
`
  return files
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const files = await generate()
  let stale = 0
  for (const [rel, text] of Object.entries(files)) {
    const path = join(outDir ?? WORKER, rel)
    const cur = existsSync(path) ? readFileSync(path, 'utf8') : null
    if (cur === text) { console.log(`${rel}: up to date`); continue }
    if (check) { console.error(`${rel}: out of date; run npm run schema:sync`); stale++; continue }
    mkdirSync(join(path, '..'), { recursive: true })
    writeFileSync(path, text)
    console.log(`${rel}: written`)
  }
  process.exit(stale ? 1 : 0)
}
