// Command tenant_seed writes worker/src/services/provision_seed.ts: the
// permission vocabulary and the default role set a new school opens with,
// taken from internal/rbac and internal/catalog so the Worker's provisioning
// (src/services/provision.ts) seeds exactly what rbac.SeedInstitution and
// rbac.SeedCatalogRoles seed in Go. Re-run after changing either package:
//
//	go run ./scripts/d1/tenant_seed > worker/src/services/provision_seed.ts
package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/school-erp/erp/internal/catalog"
	"github.com/school-erp/erp/internal/rbac"
)

type role struct {
	Key   string   `json:"key"`
	Name  string   `json:"name"`
	Perms []string `json:"perms"`
}

func main() {
	perms := [][3]string{}
	seen := map[string]bool{}
	add := func(k, m, d string) {
		if seen[k] {
			return
		}
		seen[k] = true
		perms = append(perms, [3]string{k, m, d})
	}
	for _, p := range rbac.All {
		add(p.Key, p.Module, p.Description)
	}
	// Same module and description rules as cmd/migrate seedPermissions.
	for _, r := range catalog.Roles {
		for _, sec := range r.Sections {
			for _, f := range sec.Features {
				desc := f.Summary
				if len(desc) > 240 {
					desc = desc[:237] + "..."
				}
				if desc == "" {
					desc = f.Name
				}
				add(f.Key, r.Key, desc)
			}
		}
	}

	// Tenant roles a new school opens with: rbac.SeedInstitution then
	// rbac.SeedCatalogRoles, default roles only, platform roles excluded.
	idx := map[string]int{}
	roles := []role{}
	upsert := func(key, name string, keys []string) {
		if !rbac.IsDefault(key) || rbac.PlatformRoles[key] {
			return
		}
		i, ok := idx[key]
		if !ok {
			idx[key] = len(roles)
			roles = append(roles, role{Key: key, Name: name})
			i = len(roles) - 1
		}
		roles[i].Name = name
		have := map[string]bool{}
		for _, k := range roles[i].Perms {
			have[k] = true
		}
		for _, k := range keys {
			if !have[k] {
				have[k] = true
				roles[i].Perms = append(roles[i].Perms, k)
			}
		}
	}
	for _, r := range rbac.SystemRoles {
		upsert(r.Key, r.Name, r.Permissions)
	}
	for _, r := range catalog.Roles {
		keys := []string{}
		for _, sec := range r.Sections {
			for _, f := range sec.Features {
				keys = append(keys, f.Key)
			}
		}
		upsert(r.Key, r.Name, keys)
	}

	pj, _ := json.Marshal(perms)
	rj, _ := json.Marshal(roles)
	w := os.Stdout
	fmt.Fprintln(w, "// Generated by scripts/d1/tenant_seed from internal/rbac and internal/catalog. Do not edit.")
	fmt.Fprintln(w, "// go run ./scripts/d1/tenant_seed > worker/src/services/provision_seed.ts")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "/** [key, module, description] for every permission a school's database carries. */")
	fmt.Fprintf(w, "export const PERMISSIONS: [string, string, string][] = %s\n\n", pj)
	fmt.Fprintln(w, "/** The default tenant roles and their grants (capabilities and catalog features). */")
	fmt.Fprintf(w, "export const ROLES: { key: string; name: string; perms: string[] }[] = %s\n", rj)
}
