import { lazy, type ComponentType, type LazyExoticComponent } from 'react'

/**
 * Maps a catalog feature key to the component that implements it.
 *
 * The catalog has 419 entries; this map holds the ones with a real screen and
 * a real endpoint behind them. Anything absent renders the honest placeholder
 * in FeatureRoute — a catalogued-but-unbuilt feature says so, rather than
 * showing invented data that looks live.
 *
 * This file is the single source of truth for "what is built".
 * scripts/gen_implemented.py parses it to generate internal/api/implemented_gen.go,
 * so the navigation dots the server marks `live` can never disagree with what
 * the client can actually render. Run `make catalog` after editing.
 */
export const FEATURE_COMPONENTS: Record<string, LazyExoticComponent<ComponentType>> = {
  'institution_admin.students_admissions.student_directory_student_360': lazy(() => import('./shared/StudentProfile')),
  'institution_admin.academics.academic_structure': lazy(() => import('./shared/Academics')),
  'super_admin.institution_setup.institutions_campuses': lazy(() => import('./setup/Wizard')),
  'super_admin.institution_setup.academic_year_defaults': lazy(() => import('./setup/Wizard')),
  'super_admin.platform_setup.multi_campus_configuration': lazy(() => import('./setup/Wizard')),
  'super_admin.platform_configuration.data_operations': lazy(() => import('./setup/ImportStudents')),
  'institution_admin.students_admissions.enrollment_lifecycle': lazy(() => import('./lifecycle/Certificates')),
  'super_admin.access_security.users': lazy(() => import('./super_admin/Users')),
  'super_admin.platform_setup.user_directory_provisioning': lazy(() => import('./super_admin/Users')),
  'super_admin.access_security.roles_permissions': lazy(() => import('./super_admin/RolesPermissions')),
  'super_admin.platform_setup.role_permission_matrix': lazy(() => import('./super_admin/RolesPermissions')),
  'super_admin.platform_configuration.module_configuration': lazy(() => import('./super_admin/ModuleConfiguration')),
  'super_admin.access_security.login_session_audit': lazy(() => import('./super_admin/SessionAudit')),
  'super_admin.platform_setup.login_session_audit_logs': lazy(() => import('./super_admin/SessionAudit')),
  'super_admin.platform_setup.system_health_integration_alerts': lazy(() => import('./shared/Jobs')),
  // Approvals — one queue for leave, corrections and concessions.
  'institution_admin.administration.approvals_center': lazy(() => import('./workflow/Approvals')),
  'hod.department_workspace.approvals': lazy(() => import('./workflow/Approvals')),
  'hr.hr_workspace.leave': lazy(() => import('./workflow/Approvals')),

  // Homework — the same screen from the teacher's and the child's side.
  'faculty.teaching_workspace.homework_classwork': lazy(() => import('./workflow/Homework')),
  'faculty.teaching_workspace.homework_classwork_publisher': lazy(() => import('./workflow/Homework')),
  'faculty.teaching_workspace.teacher_digital_diary': lazy(() => import('./workflow/Homework')),
  'student.student_self_service.homework_assignments': lazy(() => import('./workflow/Homework')),
  'student.student_portal.digital_assignment_upload': lazy(() => import('./workflow/Homework')),
  'parent.parent_self_service.homework_academics': lazy(() => import('./workflow/Homework')),
  'parent.parent_mobile_app.homework_subject_material': lazy(() => import('./workflow/Homework')),

  'super_admin.platform_configuration.audit_log': lazy(() => import('./super_admin/AuditLog')),

  // The vendor's back office. One screen carries the directory, provisioning,
  // the handover and the plan list, because in practice they are one job.
  'seller_admin.customers.tenant_directory': lazy(() => import('./seller/Tenants')),
  'seller_admin.customers.provision_new_school': lazy(() => import('./seller/Tenants')),
  'seller_admin.customers.suspend_reactivate': lazy(() => import('./seller/Tenants')),
  'seller_admin.customers.onboarding_progress': lazy(() => import('./seller/Tenants')),
  'seller_admin.subscriptions_billing.plans_pricing': lazy(() => import('./seller/Tenants')),
  'seller_admin.subscriptions_billing.subscription_ledger': lazy(() => import('./seller/Tenants')),
  'seller_admin.subscriptions_billing.seat_overage_renewals': lazy(() => import('./seller/Tenants')),

  'institution_admin.dashboard.executive_kpis': lazy(() => import('./principal/Dashboard')),
  'institution_admin.dashboard.campus_kpi_overview': lazy(() => import('./principal/Dashboard')),
  'institution_admin.dashboard.needs_attention': lazy(() => import('./principal/Dashboard')),
  'institution_admin.dashboard.needs_attention_widget': lazy(() => import('./principal/Dashboard')),
  'institution_admin.academic_monitoring.attendance_monitoring': lazy(() => import('./principal/AttendanceMonitoring')),
  'institution_admin.reports.comprehensive_attendance_report': lazy(() => import('./principal/AttendanceMonitoring')),
  'institution_admin.administration.staff_allocation_workload': lazy(() => import('./principal/StaffWorkload')),
  'institution_admin.administration.staff_overview': lazy(() => import('./principal/StaffWorkload')),
  'institution_admin.academics.timetable': lazy(() => import('./shared/Timetable')),
  'hod.dashboard.department_kpis': lazy(() => import('./hod/Department')),
  'hod.department_workspace.faculty_directory': lazy(() => import('./hod/Department')),
  'hod.department_workspace.faculty_allocation_workload': lazy(() => import('./hod/Department')),
  'faculty.dashboard.todays_classes': lazy(() => import('./faculty/TodaysClasses')),
  'faculty.dashboard.my_work': lazy(() => import('./faculty/MyWork')),

  // The NEP holistic card. One screen for the teacher recording observations
  // and the family reading them — the same card from two sides, and building
  // two would guarantee they drift.
  'faculty.teaching_workspace.nep_holistic_progress_card_hpc': lazy(() => import('./exams/HolisticCard')),
  'faculty.teaching_workspace.parakh_holistic_assessment_entry': lazy(() => import('./exams/HolisticCard')),
  'institution_admin.compliance.parakh_nep_credit_framework': lazy(() => import('./exams/HolisticCard')),
  'faculty.teaching_workspace.my_classes': lazy(() => import('./faculty/TodaysClasses')),
  'faculty.teaching_workspace.take_attendance': lazy(() => import('./shared/Attendance')),
  'faculty.teaching_workspace.period_wise_student_attendance': lazy(() => import('./shared/Attendance')),
  'faculty.teaching_workspace.my_timetable': lazy(() => import('./shared/Timetable')),
  'faculty.teaching_workspace.daily_timetable_view': lazy(() => import('./shared/Timetable')),
  'finance.dashboard.finance_kpis': lazy(() => import('./finance/Dashboard')),
  'finance.dashboard.needs_attention': lazy(() => import('./finance/Dashboard')),
  'finance.fee_workspace.counter_fee_collection': lazy(() => import('./finance/FeeCounter')),
  'finance.fee_finance_workspace.collect_payment': lazy(() => import('./finance/FeeCounter')),
  'finance.fee_workspace.student_ledger_360': lazy(() => import('./finance/FeeCounter')),
  'finance.fee_finance_workspace.student_ledger': lazy(() => import('./finance/FeeCounter')),
  'finance.fee_finance_workspace.receipts': lazy(() => import('./finance/FeeCounter')),
  'finance.fee_workspace.partial_advance_payment_rules': lazy(() => import('./finance/FeeCounter')),
  'finance.fee_finance_workspace.partial_advance_payments': lazy(() => import('./finance/FeeCounter')),
  'finance.fee_workspace.defaulter_tracking_aging': lazy(() => import('./finance/Defaulters')),
  'finance.fee_finance_workspace.defaulters_reminders': lazy(() => import('./finance/Defaulters')),
  'finance.fee_workspace.post_dated_cheques_pdc_registry': lazy(() => import('./finance/PDCRegister')),
  'finance.fee_workspace.cheque_bounce_fine_engine': lazy(() => import('./finance/PDCRegister')),
  'parent.parent_self_service.fees_payments': lazy(() => import('./portal/Fees')),
  'student.student_self_service.fees': lazy(() => import('./portal/Fees')),
  'parent.parent_mobile_app.one_touch_online_fee_payment': lazy(() => import('./portal/Fees')),
  'admissions.dashboard.admissions_kpis': lazy(() => import('./admissions/Dashboard')),
  'admissions.dashboard.follow_ups': lazy(() => import('./admissions/Dashboard')),
  'admissions.admissions_workspace.enquiries_leads': lazy(() => import('./admissions/Dashboard')),
  'hr.dashboard.hr_kpis': lazy(() => import('./hr/Dashboard')),
  'hr.hr_workspace.employee_master': lazy(() => import('./hr/Dashboard')),
  'hr.hr_workspace.employee_master_directory': lazy(() => import('./hr/Dashboard')),
  'operations.specialist_workspace.role_specific_home': lazy(() => import('./operations/Workspace')),
  'operations.specialist_workspace.library_role': lazy(() => import('./operations/Workspace')),
  'operations.specialist_workspace.transport_role': lazy(() => import('./operations/Workspace')),
  'operations.library_management.book_issue_return_terminal': lazy(() => import('./operations/Workspace')),
  'operations.transport_management.vehicle_master_registry': lazy(() => import('./operations/Workspace')),
  'student.dashboard.my_day': lazy(() => import('./portal/Portal')),
  'student.dashboard.action_reminders': lazy(() => import('./portal/Portal')),
  'student.student_self_service.attendance': lazy(() => import('./portal/Portal')),
  'student.student_portal.student_personalized_dashboard': lazy(() => import('./portal/Portal')),
  'student.student_self_service.timetable': lazy(() => import('./shared/Timetable')),
  'student.student_self_service.profile': lazy(() => import('./shared/Profile')),
  'parent.dashboard.child_switcher': lazy(() => import('./portal/Portal')),
  'parent.dashboard.child_summary': lazy(() => import('./portal/Portal')),
  'parent.dashboard.needs_attention': lazy(() => import('./portal/Portal')),
  'parent.parent_self_service.attendance': lazy(() => import('./portal/Portal')),
  'parent.parent_mobile_app.child_attendance_calendar': lazy(() => import('./portal/Portal')),
  'parent.parent_mobile_app.multi_child_single_login_switch': lazy(() => import('./portal/Portal')),
  'admissions.admissions_workspace.applications': lazy(() => import('./admissions/Pipeline')),
  'admissions.admissions_workspace.merit_list_generation': lazy(() => import('./admissions/Pipeline')),
  'admissions.admissions_workspace.seat_allocation_management': lazy(() => import('./admissions/Pipeline')),
  'admissions.admissions_workspace.offers_admission_decisions': lazy(() => import('./admissions/Pipeline')),
  'admissions.admissions_workspace.enrollment_handoff': lazy(() => import('./admissions/Pipeline')),
  'admissions.admissions_workspace.admitted_student_handoff': lazy(() => import('./admissions/Pipeline')),
  'admissions.admissions_workspace.admission_conversion_reports': lazy(() => import('./admissions/Pipeline')),
  'admissions.admissions_workspace.rte_right_to_education_quota_tracking': lazy(() => import('./admissions/Pipeline')),
  'institution_admin.students_admissions.admissions_overview': lazy(() => import('./admissions/Pipeline')),
  'faculty.teaching_workspace.marks_entry': lazy(() => import('./exams/Gradebook')),
  'faculty.teaching_workspace.gradebook': lazy(() => import('./exams/Gradebook')),
  'faculty.teaching_workspace.cbse_gradebook_marks_entry': lazy(() => import('./exams/Gradebook')),
  'faculty.teaching_workspace.icse_gradebook_entry': lazy(() => import('./exams/Gradebook')),
  'faculty.teaching_workspace.state_board_gradebook_entry': lazy(() => import('./exams/Gradebook')),
  'institution_admin.academic_monitoring.exams_result_status': lazy(() => import('./exams/ReportCards')),
  'institution_admin.reports.exam_grade_analytics': lazy(() => import('./exams/ReportCards')),
  'student.student_self_service.exams_grades': lazy(() => import('./portal/Results')),
  'parent.parent_self_service.results_report_cards': lazy(() => import('./portal/Results')),
  'parent.parent_mobile_app.digital_report_card_downloads': lazy(() => import('./portal/Results')),
  'institution_admin.students_admissions.certificates_documents': lazy(() => import('./lifecycle/Certificates')),
  'institution_admin.administration.digital_certificate_generation': lazy(() => import('./lifecycle/Certificates')),
  'institution_admin.academics.class_section_promotion': lazy(() => import('./lifecycle/Certificates')),
  'institution_admin.administration.communication': lazy(() => import('./comms/Circulars')),
  'institution_admin.administration.circular_announcement_dispatch': lazy(() => import('./comms/Circulars')),
  'parent.parent_self_service.communication': lazy(() => import('./comms/Circulars')),
  'student.student_self_service.announcements_messages': lazy(() => import('./comms/Circulars')),
  'institution_admin.compliance.udise_return_preparation': lazy(() => import('./compliance/UDISE')),
  'institution_admin.compliance.apaar_id_register': lazy(() => import('./compliance/UDISE')),
  'institution_admin.compliance.statutory_registers': lazy(() => import('./compliance/UDISE')),
  'super_admin.platform_setup.udise_data_sync': lazy(() => import('./compliance/UDISE')),
  'super_admin.platform_setup.apaar_id_provisioning': lazy(() => import('./compliance/UDISE')),
  'hr.hr_workspace.payroll': lazy(() => import('./payroll/Payroll')),
  'hr.hr_workspace.payroll_calculation_engine': lazy(() => import('./payroll/Payroll')),
  'hr.hr_workspace.payslip_generation_email_dispatch': lazy(() => import('./payroll/Payroll')),
  'hr.hr_workspace.salary_structure_builder': lazy(() => import('./payroll/Payroll')),
  'operations.hostel_management.room_allocation_engine': lazy(() => import('./ops2/Hostel')),
  'operations.hostel_management.hostel_building_room_setup': lazy(() => import('./ops2/Hostel')),
  'operations.specialist_workspace.hostel_role': lazy(() => import('./ops2/Hostel')),
  'operations.inventory_stores.item_category_store_setup': lazy(() => import('./ops2/Inventory')),
  'operations.inventory_stores.department_stock_issuance': lazy(() => import('./ops2/Inventory')),
  'operations.specialist_workspace.inventory_stores_role': lazy(() => import('./ops2/Inventory')),
}

export function componentFor(key: string) {
  return FEATURE_COMPONENTS[key]
}
