// GENERATED by scripts/schema-sync.mjs. Do not edit.
// Every tenant migration db/tenant.sql already contains; provisioning records
// them in a new school's _migrations so the runner never re-applies them.
export const TENANT_MIGRATIONS: ReadonlyArray<{ version: number; name: string; checksum: string }> = [
  { version: 1, name: 'baseline', checksum: '9a4a44c3446aaf329c71f4b3c6e711c51dbc8fed1e50cef32cf0a3f0ce120f87' },
  { version: 2, name: 'ai_warnings', checksum: '0f8344df6470633822b91a572b64501625fcf0a5982a45c96299ea4b6f2631e2' },
  { version: 3, name: 'ai_briefs', checksum: '6dcef06668a4c85f68e7c2344964d13e875ba02b1995c8f2b60f9c4ff233d236' },
  { version: 4, name: 'enquiry_activity', checksum: '2e4d2e29b0872c56c175c3c7bbb0f5c73c94cfd3987c8e2447ec1908cabfe4b8' },
  { version: 5, name: 'session_activity', checksum: '4bf89c2455eec680ca76661992b66198e675bce8475640648312620be65077b6' },
  { version: 6, name: 'concerns_pipeline', checksum: '8af8accb30a7e5ba5ddc0f4a177fd5b6c580d7964e8d562cac0298e52f7eb81d' },
  { version: 7, name: 'lms', checksum: '3339a640a822aabec2d70e28dbea2785f8012340a6d4da877bcc1f62a21d17f3' },
  { version: 8, name: 'lms_admin', checksum: '0c3b8afdc233a5b4a1128b1b462f593048a08dbbd21dbc7c64da9b6cf9be7332' },
  { version: 9, name: 'lms_videos', checksum: 'b7947e5608afc2df8dd71f0d11a6b9029d659562a5b3f7a27bd408ccc4a9c63c' },
  { version: 10, name: 'ai_warning_dismissals', checksum: '79e1cd120c3e534d082e28c806ca1ad7f9de76c40cd30532371637a77b4c3d91' },
  { version: 11, name: 'lms_modules', checksum: '186f731b38bac89604e9f5412f26501c0fe88b80f97f851e3773567a6d1d4906' },
  { version: 12, name: 'lms_progression', checksum: '4f6511af475fbf4fb76bdabf8185f9f3cfda1275070a90361570eca894b95599' },
  { version: 14, name: 'messaging_delivery', checksum: '93c01ff8c7ca13f052e16a097c7ae407bf335a3e6dc70e8bdd254c6e14e9c00d' },
  { version: 15, name: 'query_indexes', checksum: '7c9aa0d04c1b91ae50c0bc4e864d0779768b78b2675d9f7100505d2aa0e0dbf2' },
]
