// GENERATED by scripts/schema-sync.mjs. Do not edit.
// Every tenant migration db/tenant.sql already contains; provisioning records
// them in a new school's _migrations so the runner never re-applies them.
export const TENANT_MIGRATIONS: ReadonlyArray<{ version: number; name: string; checksum: string }> = [
  { version: 1, name: 'baseline', checksum: '9a4a44c3446aaf329c71f4b3c6e711c51dbc8fed1e50cef32cf0a3f0ce120f87' },
]
