#!/usr/bin/env python3
"""Generate docs/FEATURES.md — one documented entry per catalog feature.

Every one of the 419 features gets a row carrying its permission key, data
scope, status and (where built) the endpoints behind it. Written from the same
CSV and registry the code is generated from, so the documentation cannot drift
from what actually ships.
"""

import csv
import json
import pathlib
import re
import sys
from collections import OrderedDict

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
from gen_catalog import ROLE_KEYS, ROLE_ORDER, SCOPE_MAP, AMBIGUOUS, BY_ROLE_SCOPE, slug  # noqa: E402

CSV_PATH = ROOT / "docs" / "edu_features.csv"
REGISTRY = ROOT / "web" / "src" / "features" / "registry.ts"
OUT = ROOT / "docs" / "FEATURES.md"

SCOPE_DOC = {
    "platform": ("Platform", "Every institution. Requires `app.is_platform_admin`."),
    "institution": ("Institution", "The caller's tenant. Enforced by Postgres RLS."),
    "campus": ("Campus", "Campuses named on the user's role assignments."),
    "department": ("Department", "Departments where `departments.head_user_id` is the caller."),
    "assigned_classes": ("Assigned classes", "Sections the caller teaches or is class teacher of."),
    "self": ("Self", "The caller's own student record."),
    "children": ("Linked children", "Students the caller is a guardian of."),
}

# Endpoints and implementing screens come from docs/feature_map.json, which
# gen_matrix.py builds by reading the components' own source. This used to be a
# hand-maintained dict here, and it silently rotted the moment the sections were
# regrouped: every key in it named a slug that no longer existed, so the API
# column of this document read "—" for all 144 built features while looking
# authoritative.
FEATURE_MAP = ROOT / "docs" / "feature_map.json"


def built_details():
    """key -> (component, [endpoints]) for everything with a screen."""
    if not FEATURE_MAP.exists():
        return {}
    out = {}
    for f in json.loads(FEATURE_MAP.read_text()):
        if not f.get("built"):
            continue
        eps = []
        for e in f.get("endpoints", []):
            for m in e.get("methods") or ["GET"]:
                eps.append(f"{m} {e['path']}")
        out[f["key"]] = ((f.get("component") or "").split("/")[-1], sorted(set(eps)))
    return out


def implemented_keys():
    src = REGISTRY.read_text()
    body = src[src.index("FEATURE_COMPONENTS"):]
    return set(re.findall(r"^\s*'([a-z0-9_]+\.[a-z0-9_]+\.[a-z0-9_]+)':", body, re.M))


def main() -> int:
    built = implemented_keys()
    rows = list(csv.DictReader(CSV_PATH.open()))

    roles = OrderedDict()
    for r in rows:
        rk = ROLE_KEYS[r["Role"].strip()]
        raw = r["Data Scope"].strip()
        scope = BY_ROLE_SCOPE[rk] if raw in AMBIGUOUS else SCOPE_MAP[raw]
        section = r["Section"].strip()
        feature = r["Feature"].strip()
        workspace = (r.get("Workspace") or section).strip()
        key = f"{rk}.{slug(section)}.{slug(feature)}"
        roles.setdefault(rk, {"name": r["Role"].strip(), "ws": OrderedDict()})
        groups = roles[rk]["ws"].setdefault(workspace, OrderedDict())
        groups.setdefault(section, []).append({
            "key": key, "name": feature, "scope": scope,
            "summary": r["What User Sees & Does"].strip(),
            "tier": (r.get("Tier") or "core").strip(),
            "built": key in built,
        })

    ordered = OrderedDict((k, roles[k]) for k in ROLE_ORDER if k in roles)
    def feats(role):
        return [f for g in role["ws"].values() for fs in g.values() for f in fs]

    total = sum(len(feats(r)) for r in ordered.values())
    nbuilt = sum(1 for r in ordered.values() for f in feats(r) if f["built"])
    details = built_details()

    out = []
    w = out.append
    w("# Feature reference\n\n")
    w(f"Every feature in the catalog: **{total} features** across **{len(ordered)} roles** "
      f"and **{sum(len(r['ws']) for r in ordered.values())} workspaces**. "
      f"**{nbuilt}** have a working screen and endpoint; the rest are registered with their "
      "permission and data scope, navigable, and render an explicit "
      "\"catalogued, not implemented\" page.\n\n")
    w("Generated by `scripts/gen_docs.py` from [edu_features.csv](edu_features.csv) and the SPA's "
      "component registry. Do not edit by hand — run `make docs`.\n\n")

    w("## How to read this\n\n")
    w("| Column | Meaning |\n|---|---|\n")
    w("| **Feature** | The screen, as named in the source catalog. |\n")
    w("| **Permission key** | Row in `permissions`, granted through `role_permissions`. "
      "The API gates on it and the SPA builds navigation from it. |\n")
    w("| **Scope** | The data boundary. See below. |\n")
    w("| **Tier** | How prominent it is in navigation. `core` is listed normally; "
      "`advanced` sits behind a disclosure in its group; `optional` is catalogued and "
      "routable but never in default navigation. Tier never affects authorisation. |\n")
    w("| **Status** | ✅ built · ○ catalogued |\n")
    w("| **Screen · API** | The React component behind a built feature and the endpoints "
      "it calls, read from the component's own source. |\n\n")

    w("## Navigation shape\n\n")
    w("A role owns **workspaces**; a workspace holds **groups**; a group holds features. "
      "That nesting is the navigation itself — a person sees only the workspace names in "
      "their sidebar, and the groups appear when they open one.\n\n")

    w("## Data scopes\n\n")
    w("| Scope | Boundary | Enforced by |\n|---|---|---|\n")
    for _, (label, desc) in SCOPE_DOC.items():
        by = ("Postgres RLS" if label in ("Platform", "Institution")
              else "`internal/scope` + explicit SQL predicate")
        w(f"| **{label}** | {desc} | {by} |\n")
    w("\nRLS covers only the tenant boundary. The four narrower scopes are enforced in the "
      "application, because every row involved belongs to the same institution and the "
      "`tenant_isolation` policy admits all of them. A handler that forgets its scope filter "
      "leaks data *within* a tenant — which is why `internal/scope` returns `FALSE` for an "
      "empty set rather than omitting the clause.\n\n")

    w("## Roles at a glance\n\n")
    w("| Role | Key | Workspaces | Features | Core | Built | Demo login |\n"
      "|---|---|---:|---:|---:|---:|---|\n")
    for rk, role in ordered.items():
        fs = feats(role)
        core = sum(1 for f in fs if f["tier"] == "core")
        b = sum(1 for f in fs if f["built"])
        w(f"| {role['name']} | `{rk}` | {len(role['ws'])} | {len(fs)} | {core} | {b} | "
          f"`{rk}@vivencia.test` |\n")
    w("\n")

    for rk, role in ordered.items():
        fs = feats(role)
        b = sum(1 for f in fs if f["built"])
        w(f"---\n\n## {role['name']}\n\n")
        w(f"`{rk}` · {len(role['ws'])} workspaces · {len(fs)} features · {b} built · "
          f"sign in as `{rk}@vivencia.test`\n\n")
        w("Workspaces: " + " · ".join(f"**{n}**" for n in role["ws"]) + "\n\n")

        for wsname, groups in role["ws"].items():
            n = sum(len(g) for g in groups.values())
            w(f"### {wsname}\n\n")
            w(f"*{n} features in {len(groups)} "
              f"{'group' if len(groups) == 1 else 'groups'}.*\n\n")
            for gname, items in groups.items():
                if len(groups) > 1 or gname != wsname:
                    w(f"#### {gname}\n\n")
                w("| Feature | What it does | Permission key | Scope | Tier | Status | Screen · API |\n")
                w("|---|---|---|---|---|:--:|---|\n")
                for f in items:
                    comp, eps = details.get(f["key"], ("", []))
                    if comp:
                        api = f"`{comp}`"
                        if eps:
                            api += "<br>" + "<br>".join(f"`{x}`" for x in eps[:4])
                    else:
                        api = "—"
                    summary = f["summary"].replace("|", "\\|")
                    w(f"| **{f['name']}** | {summary} | `{f['key']}` | {f['scope']} | "
                      f"{f['tier']} | {'✅' if f['built'] else '○'} | {api} |\n")
                w("\n")

    OUT.write_text("".join(out))
    print(f"docs: {total} features documented, {nbuilt} built → {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
