#!/usr/bin/env python3
"""Generate internal/api/implemented_gen.go from web/src/features/registry.ts.

The client decides what is built (it holds the components); the server has to
agree, because it marks features `live` for the navigation dots and the docs.
Parsing the registry keeps one source of truth instead of two lists that
silently diverge the first time someone ships a screen.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
REG = ROOT / "web" / "src" / "features" / "registry.ts"
OUT = ROOT / "internal" / "api" / "implemented_gen.go"

src = REG.read_text()
body = src[src.index("FEATURE_COMPONENTS"):]
keys = re.findall(r"^\s*'([a-z0-9_]+\.[a-z0-9_]+\.[a-z0-9_]+)':", body, re.M)
if not keys:
    print("no feature keys found in registry.ts", file=sys.stderr)
    sys.exit(1)

keys = sorted(set(keys))
lines = [
    "// Code generated by scripts/gen_implemented.py from web/src/features/registry.ts. DO NOT EDIT.\n\n",
    "package api\n\n",
    "// implementedFeatures lists catalog keys with a working screen and endpoint.\n",
    "//\n",
    "// Derived from the SPA's component registry so the server can never claim a\n",
    "// feature is live when the client has nothing to render for it.\n",
    f"// {len(keys)} of the catalog's features are implemented.\n",
    "var implementedFeatures = map[string]bool{\n",
]
lines += [f'\t"{k}": true,\n' for k in keys]
lines.append("}\n")
OUT.write_text("".join(lines))
print(f"implemented: {len(keys)} features")
