#!/usr/bin/env python3
"""Generate internal/api/implemented_gen.go from the SPA's feature registry.

The client decides what is built (it holds the components); the server has to
agree, because it marks features `live` for the navigation dots and the docs.
Parsing the registry keeps one source of truth instead of two lists that
silently diverge the first time someone ships a screen.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
REG = ROOT / "web" / "src" / "features" / "registry.ts"
OUT = ROOT / "internal" / "api" / "implemented_gen.go"

KEY = re.compile(r"^\s*'([a-z0-9_]+\.[a-z0-9_]+\.[a-z0-9_]+)':", re.M)

src = REG.read_text()
keys = KEY.findall(src[src.index("FEATURE_COMPONENTS"):])

# Per-domain key fragments (`*keys*.ts` beside the screens they name).
#
# Several agents build screens at once and none of them may edit registry.ts,
# so each hands over its own map and registry.ts spreads them. A generator that
# read only registry.ts would find the spread and none of the keys inside it,
# and the server would then report those screens as unbuilt while the client
# happily rendered them — the exact divergence this file exists to prevent.
for frag in sorted((ROOT / "web" / "src" / "features").rglob("*keys*.ts")):
    keys += KEY.findall(frag.read_text())

if not keys:
    print("no feature keys found in the registry or its fragments", file=sys.stderr)
    sys.exit(1)

keys = sorted(set(keys))
lines = [
    "// Code generated by scripts/gen_implemented.py from the SPA feature registry. DO NOT EDIT.\n\n",
    "package api\n\n",
    "// implementedFeatures lists catalog keys with a working screen and endpoint.\n",
    "//\n",
    "// Derived from the SPA's component registry so the server can never claim a\n",
    "// feature is live when the client has nothing to render for it.\n",
    f"// {len(keys)} of the catalog's features are implemented.\n",
    "var implementedFeatures = map[string]bool{\n",
]
# Pad the values into a column the way gofmt would, so `make catalog` is a
# no-op when gofmt is unavailable and the generated file never shows up in a
# diff as pure whitespace churn.
_width = max((len(k) for k in keys), default=0) + 3  # quotes and the colon
lines += [f'\t{(chr(34) + k + chr(34) + ":").ljust(_width)} true,\n' for k in keys]
lines.append("}\n")
OUT.write_text("".join(lines))
print(f"implemented: {len(keys)} features")
