# -*- coding: utf-8 -*-
"""The chains: press here, and check it landed there.

A list of screens tells a reviewer what exists. It does not tell them that
locking payroll is what lets finance draw the bank file, or that a transport
allocation is what puts a fee on a child's demand and a bus on their parent's
phone. Those are the things that break, and they break between two roles, so
nobody holding one login ever sees both ends.

So each row is one action, and says: who presses it, what happens, what moves
somewhere else, and whose account to open to see that it did.

`verified` is honest. 'code' means the link was read in the source this sheet
was built against; 'check' means it follows from how the screens are wired and
should be confirmed on the day. Nothing here is a guess dressed as a fact.
"""

# flow, step, role, screen, action, what happens, reflects to, where to verify, verified
CHAINS = [
 # ---------------------------------------------------------------- payroll
 ('A. Salary month', 1, 'Faculty / HOD', 'Staff attendance register', 'Mark staff present / absent / late',
  'The day is recorded against each employee.',
  'This is the only source of loss of pay. Nothing else feeds it.',
  'HR & Payroll > Staff attendance register: the same marks.', 'code'),
 ('A. Salary month', 2, 'Institution Admin', 'Leave rules & LOP', 'Set the policy',
  'Half-day fraction, grace minutes, how many late marks make one LOP day, whether absent / unpaid leave / exhausted quota cost pay, rounding, and a monthly cap.',
  'Changes what the same attendance turns into. Change the policy and the payroll figure changes with no attendance edited.',
  'HR & Payroll > Payroll > Run payroll: the LOP days move.', 'code'),
 ('A. Salary month', 3, 'Staff member', 'My profile > Leave', 'Apply for leave',
  'A request goes to the approver.',
  'Approved paid leave protects the day. Unpaid leave, or leave past the quota, becomes LOP if the policy says so.',
  'HR & Payroll > Leave: the request. Then Payroll: the LOP days.', 'check'),
 ('A. Salary month', 4, 'HR & Payroll', 'Payroll > Run payroll', 'Run payroll',
  'Builds a payslip per employee from the salary structure, minus LOP. If any staff have no attendance at all it stops and says how many, because their days would silently be paid in full.',
  'Creates the month in draft. Nothing has moved yet.',
  'The payslip table fills; Gross, Deductions and Net appear.', 'code'),
 ('A. Salary month', 5, 'HR & Payroll', 'Payroll', 'Lock payroll & send to finance',
  'The month goes draft -> locked. Attendance can no longer change the figures.',
  'THIS is the handover. Finance can now draw the bank file; until it is locked they cannot.',
  'Accounts & Finance > Approve & pay salaries > Release the money.', 'code'),
 ('A. Salary month', 6, 'Accounts & Finance', 'Approve & pay salaries', 'Download bank file',
  'Produces the file for the bank portal. It does NOT send money.',
  'Nobody has been paid. The file existing is not a payment.',
  'Open the file; check the net figures match the payroll register.', 'code'),
 ('A. Salary month', 7, 'Accounts & Finance', 'Approve & pay salaries', 'Mark as paid',
  'locked -> paid.',
  'Unlocks the Publish payslips step.',
  'The card title becomes Paid.', 'code'),
 ('A. Salary month', 8, 'HR & Payroll', 'Payroll', 'Publish payslips',
  'paid -> published, and writes ONE NOTIFICATION PER EMPLOYEE.',
  'Every member of staff gets a bell notification linking to My pay. This is the step the staff actually feel.',
  'Sign in as any staff member: the bell, then My profile > My pay.', 'code'),
 ('A. Salary month', 9, 'HR & Payroll', 'Payroll', 'Unlock',
  'locked -> draft.',
  'Finance loses the bank file again. Use it to prove the gate works both ways.',
  'Finance: Release the money should refuse to draw a file.', 'code'),

 # ------------------------------------------------------------------- fees
 ('B. Fees', 1, 'Institution Admin / Finance', 'Fee setup', 'Create the fee structure for a class',
  'Heads and amounts for the class.',
  'Every child enrolled in that class inherits it. Nothing is charged yet.',
  'Finance > Fee dashboard.', 'check'),
 ('B. Fees', 2, 'Finance', 'Fee demands', 'Raise the demand',
  'Turns the structure into an invoice per child.',
  'The parent can now see an amount due, and the child appears in Who has not paid.',
  'Parent login > Fees & payments: the amount.', 'check'),
 ('B. Fees', 3, 'Finance / Front office', 'Take fee payment', 'Take a payment',
  'Records the money and produces a receipt number.',
  'Parent sees the receipt. The day book, cash book and collection report all move. The child leaves the defaulters list.',
  'Parent > Fees & payments > Receipts (Download). Finance > Daybook & cashbook.', 'code'),
 ('B. Fees', 4, 'Parent', 'Fees & payments > Receipts', 'Download',
  'Saves the same A4 receipt the counter prints, as a PDF.',
  'Nothing changes in the school. This is a read.',
  'The PDF opens and shows the school letterhead.', 'code'),
 ('B. Fees', 5, 'Finance', 'Take fee payment', 'Bounce a cheque',
  'The payment is marked not cleared.',
  'The receipt is watermarked, and the child goes back onto the dues list.',
  'Who has not paid: the child returns.', 'code'),
 ('B. Fees', 6, 'Finance', 'Match bank records', 'Reconcile',
  'Matches the bank statement against what the software recorded.',
  'This is the only place that tells you money actually arrived.',
  'The matched rows.', 'check'),

 # -------------------------------------------------------------- transport
 ('C. Transport', 1, 'Transport Manager', 'Vehicles', 'Add a bus with its capacity and paper expiry dates',
  'The bus exists.',
  'Capacity feeds the over-capacity warning. Expiry dates feed the Transport desk warnings.',
  'Transport desk: a bus whose insurance lapses within 30 days is listed.', 'code'),
 ('C. Transport', 2, 'Transport Manager', 'Drivers & attendants', 'Assign a driver to a bus',
  'The driver is on that bus.',
  'Try the same driver on a second active bus: it refuses and names the first, because the phone could not tell which bus it was signing into.',
  'The refusal message names the other bus.', 'code'),
 ('C. Transport', 3, 'Transport Manager', 'Routes & stops', 'Add stops with times and a fare',
  'The route has an ordered list of stops.',
  'The fare lives on the STOP. It is what a child allocated there will be charged.',
  'Student allocation: the fare shown matches the stop.', 'code'),
 ('C. Transport', 4, 'Transport Manager', 'Student allocation', 'Allocate a child',
  'One row ties child -> route -> stop, from today.',
  'FOUR THINGS AT ONCE: a transport fee goes on the child fee demand; the child appears on the route register; the parent can see the bus; and the family becomes reachable from transport Messages.',
  'Parent login > My Child’s Bus, and > Fees & payments.', 'code'),
 ('C. Transport', 5, 'Transport Manager', 'Student allocation', 'Allocate a child who is already on another route',
  'A warning names the old route and the day it ends; the button becomes Move this child.',
  'Saving ends the old allocation and starts the new one. The old one is closed, not deleted, so a fee already raised stays explicable.',
  'The old route no longer lists the child; the new one does.', 'code'),
 ('C. Transport', 6, 'Transport Manager', 'Student allocation', 'Allocate past the bus capacity',
  'Warns that the bus seats N and this makes N+1.',
  'It WARNS, it does not block. Pressing again saves.',
  'The child is allocated; the warning was advice.', 'code'),
 ('C. Transport', 7, 'Transport Manager', 'Driver Phone Tracker', 'Generate a pair code',
  'A short-lived code.',
  'Nothing until a driver uses it.',
  'The code appears.', 'code'),
 ('C. Transport', 8, 'Driver', 'erp.xulo.in/bus-tracker/', 'Enter the code and sign in',
  'That handset becomes the bus GPS.',
  'Transport Manager sees the handset paired and last seen.',
  'Driver Phone Tracker: paired, seconds ago.', 'code'),
 ('C. Transport', 9, 'Driver', 'bus-tracker app', 'Scan the bus sticker, pick the route, Start run',
  'A trip opens.',
  'Today’s runs flips to Running with a departure time. Live vehicle tracking draws the bus. The PARENT sees it move.',
  'Transport Manager > Today’s runs, and Parent > My Child’s Bus.', 'code'),
 ('C. Transport', 10, 'Transport Manager', 'Safety checks', 'Fail an item (e.g. tyres)',
  'The check is recorded as not cleared.',
  'Transport desk names it: "<bus> failed its morning check: tyres". It does NOT stop the bus - at 7:02 the children are at the stop.',
  'Transport desk, and Today’s runs shows Check failed.', 'code'),
 ('C. Transport', 11, 'Attendant / Transport Manager', 'Route attendance', 'Mark On / Off / Absent',
  'The boarding is recorded.',
  'Today’s runs: Marked rises, Not scanned falls. A child nobody looked at stays visible as not scanned.',
  'Today’s runs counts.', 'code'),
 ('C. Transport', 12, 'Transport Manager', 'Delays & exceptions', 'Log a breakdown',
  'An open incident.',
  'Transport desk says N incidents still open; the route card gets a badge.',
  'Resolve it and both clear.', 'code'),
 ('C. Transport', 13, 'Parent', 'My Child’s Bus', '(read only)',
  'Shows route, bus, driver, stop, scheduled time; while running, the map, metres away, ETA and the driver’s number.',
  'Turn the driver’s phone off: it must go no signal, then stale. It must never show a frozen bus as live.',
  'Watch the state change.', 'code'),
 ('C. Transport', 14, 'Institution Admin', 'Tracking policy', 'Switch off "parents may watch"',
  'Parents see not published.',
  'The position and the driver number are STRIPPED ON THE SERVER, not hidden in the page.',
  'Parent: no map at all.', 'code'),

 # ---------------------------------------------------------- student daily
 ('D. Attendance', 1, 'Faculty', 'Take attendance', 'Mark the class',
  'Present / absent per child.',
  'Parent sees it. The absentee follow-up list builds. The admin attendance overview moves.',
  'Parent > Attendance. Institution Admin > Attendance overview.', 'check'),
 ('D. Attendance', 2, 'Institution Admin', 'Attendance overview', '(read)',
  'Which sections have not marked today.',
  'Chases the teacher, not the child.',
  'A section with no attendance is listed.', 'check'),
 ('D. Attendance', 3, 'Faculty', 'Absentee follow-up', 'Record the call home',
  'The reason is kept against the absence.',
  'Parent-facing attendance now has an explanation beside the absence.',
  'Parent > Attendance.', 'check'),

 # ------------------------------------------------------------------ exams
 ('E. Exams', 1, 'Exam Controller', 'Exams & papers', 'Create the exam and its subjects',
  'The exam exists with dates.',
  'Marks entry opens for teachers; hall tickets and seating become possible.',
  'Faculty > Marks entry lists the exam.', 'check'),
 ('E. Exams', 2, 'Exam Controller', 'Hall tickets & seating', 'Allocate seats',
  'Each candidate gets a hall, row and seat. Re-running replaces the whole allocation.',
  'Neighbours are drawn from different sections on purpose.',
  'The seating plan prints; the child’s hall ticket shows the seat.', 'code'),
 ('E. Exams', 3, 'Faculty', 'Marks entry', 'Enter marks',
  'Marks against the paper.',
  'Goes to moderation if the school uses it, then to the report card.',
  'HOD > Mark moderation.', 'check'),
 ('E. Exams', 4, 'HOD / Exam Controller', 'Mark moderation', 'Approve',
  'Marks are settled.',
  'Report cards can be produced.',
  'Report cards.', 'check'),
 ('E. Exams', 5, 'Exam Controller', 'Report cards', 'Publish',
  'The result is released.',
  'PARENT and STUDENT see results. This is the most visible single action in the product.',
  'Parent > Results & report cards. Student > Exams & grades.', 'check'),

 # ------------------------------------------------------------- admissions
 ('F. Admission', 1, 'Admissions', 'Enquiries', 'Log an enquiry',
  'A lead.',
  'Follow-up calls and campus visits hang off it; dropped leads record why.',
  'Admission reports.', 'check'),
 ('F. Admission', 2, 'Admissions', 'Application forms', 'Take an application',
  'An applicant record.',
  'Document verification then admission.',
  'The pipeline moves.', 'check'),
 ('F. Admission', 3, 'Admissions', 'Fee & enrollment', 'Admit the child',
  'The applicant becomes a student with an admission number and a class.',
  'EVERYTHING downstream starts here: the class roll, the fee demand, attendance, the parent login.',
  'Institution Admin > Student 360.', 'check'),
 ('F. Admission', 4, 'Institution Admin', 'Logins & access', 'Issue the parent login',
  'Credentials go out.',
  'The family can sign in and sees exactly their own child.',
  'Sign in as that parent.', 'code'),

 # -------------------------------------------------------------- messaging
 ('G. Messages', 1, 'Parent', 'Communication', 'Write to a teacher',
  'A thread, only with staff who teach the child.',
  'The teacher gets it in Messages > Parents.',
  'Faculty > Messages > Parents.', 'code'),
 ('G. Messages', 2, 'Transport Manager', 'Messages > Parents', 'Write to a family',
  'A thread.',
  'ONLY families whose child has a live bus allocation appear. Take the child off the bus and the family disappears from this list the same day.',
  'Remove the allocation, reload Messages.', 'code'),
 ('G. Messages', 3, 'Faculty', 'Class Status', 'Post a status',
  'A class-wall post.',
  'Parents of that class get a notification; the audience can be changed after posting by an institution admin.',
  'Parent > the feed, and the bell.', 'code'),
 ('G. Messages', 4, 'Parent', 'Concerns', 'Raise a concern',
  'A grievance under a category (transport, fees, academic...).',
  'Routed to whoever the school set for that category; the parent sees the reply and can reopen.',
  'Institution Admin > Grievances.', 'code'),

 # ---------------------------------------------------------------- library
 ('H. Library', 1, 'Librarian', 'Issue & return', 'Issue a book',
  'The copy is on loan with a due date.',
  'The student sees it; overdue builds a fine.',
  'Student > Library. Librarian > Overdue.', 'check'),
 ('H. Library', 2, 'Librarian', 'Fines', 'Record / waive a fine',
  'The fine is set or cleared.',
  'Check whether it reaches the family fee demand or stays a library matter - confirm on the day.',
  'Parent > Fees & payments: look for it.', 'check'),

 # ------------------------------------------------------------ certificates
 ('I. Certificates', 1, 'Parent', 'Certificate requests', 'Request a certificate',
  'A request.',
  'The office sees it in Certificates & transfers.',
  'Institution Admin > Certificates & transfers.', 'code'),
 ('I. Certificates', 2, 'Institution Admin', 'Certificates & transfers', 'Issue',
  'The certificate is produced on the school design, previewed, then printed.',
  'A TC carries fees outstanding and attendance; other certificates deliberately leave those out.',
  'Print it and read what is on it.', 'code'),
]

FLOW_NOTE = {
 'A. Salary month': 'Attendance becomes money. The one chain where a wrong tick in week one is a wrong bank file in week five.',
 'B. Fees': 'Money coming in, from the structure through the counter to the parent and the day book.',
 'C. Transport': 'One allocation row is a fee, a register line, a parent map and a messaging right. Test it hardest.',
 'D. Attendance': 'The daily mark, and who chases whom when it is missing.',
 'E. Exams': 'Ends at the single most visible action in the product: publishing a result.',
 'F. Admission': 'Where a child enters the system. Everything else hangs off step 3.',
 'G. Messages': 'Who may write to whom, and why the transport office can only reach bus families.',
 'H. Library': 'Short chain. The fine question is worth settling before a real school uses it.',
 'I. Certificates': 'A parent asks, the office issues, the paper carries different things depending on the kind.',
}

LOGINS = [
 ('Institution Admin / Principal', 'ramesh', 'sees everything; use it to set policy and to check other roles’ work'),
 ('Transport Manager', 'driver@jsm.test', 'transport only - the clean role view, with none of the admin extras'),
 ('Driver', 'qb9.eixie@gmail.com', 'the driver web view; the phone app is erp.xulo.in/bus-tracker/'),
 ('Parent', 'sonynag1122@gmail.com', 'Nikhil Gupta’s guardian, on the HANUMAKONDA route'),
 ('Parent (second)', '9840000011', 'the other parent login used in testing'),
]
