# -*- coding: utf-8 -*-
"""The test script: one named person, one named child, one exact value.

"Mark staff present" is not a test. It does not say whose attendance, on what
day, or what the number should be afterwards -- so two people run it two ways
and neither can say whether it passed. Every row here names the login, the
path, the value to type, and the figure to expect, and then names the second
login to open and what must have appeared there.

The cast is fixed on purpose. One member of staff, one parent, one child,
through every flow: the same Aditya Sharma in the fee chain, the attendance
chain and the message chain, so a tester builds a picture of one family rather
than meeting a new name every row.

All of it is JSM. Yajur is a real school with real parents.
"""

# --- the cast, all of them real rows on JSM --------------------------------
CAST = [
 ('ADMIN', 'ramesh', 'M2FG-YRAK-9MEA',
  'Institution Admin. Can switch workspace (top left) to HR & Payroll, Accounts & Finance, Transport Manager.'),
 ('STAFF / TRANSPORT', 'driver@jsm.test', 'Onrolonrol@ai',
  'Transport Manager role, and employee DRV-002 - so this login is also the "staff member" whose payslip you check.'),
 ('PARENT', '9840000011', '9840000011',
  'Suresh Sharma, father of Aditya Sharma (ADM0011), Grade 6 B.'),
 ('PARENT 2', 'sonynag1122@gmail.com', '(reset it in Logins & access)',
  'Sony Nagireddy, guardian of Nikhil Gupta (ADM0019), Grade 6 B - the child already on the HANUMAKONDA bus.'),
 ('DRIVER PHONE', 'erp.xulo.in/bus-tracker/', 'pair code from the office',
  'Not a normal login. Bus TS09 UB 4412, sticker code 329620, driver DRV-002.'),
]

FACTS = [
 ('Child A', 'Aditya Sharma, ADM0011, Grade 6 B - parent login 9840000011'),
 ('Child B', 'Nikhil Gupta, ADM0019, Grade 6 B - on HANUMAKONDA, stop PUBLIC GARDEN'),
 ('Bus', 'TS09 UB 4412, Tata Starbus, 32 seats, sticker 329620, driver DRV-002'),
 ('Route (active)', 'HANUMAKONDA, 4 stops, 1 child, NO BUS YET - you assign one in setup'),
 ('Route (inactive)', 'Route 1 - Kompally to school, 3 stops, 10 children, never appears in Today’s runs'),
 ('Payroll month to use', 'July 2026 - 9 staff, paid and published. October 2026 has no run at all.'),
 ('A real unpaid invoice', 'Sara Rao ADM0028, INV/2026-27/00028, ₹11,833.38 outstanding'),
]

# flow, #, sign in as, go to, do exactly this, you should see, then sign in as,
# go to, you should see there, verified
CHAINS = [
 # ------------------------------------------------------------------ setup
 ('0. Setup first', 1, 'ramesh / M2FG-YRAK-9MEA', 'Transport Manager workspace (bus icon) > Routes & stops',
  'Select route HANUMAKONDA. Set Vehicle from "(none)" to "TS09 UB 4412". Save.',
  'The route row now shows TS09 UB 4412.',
  'same login', 'Transport desk (house icon)',
  'The line "HANUMAKONDA has no bus." is GONE. Today’s runs shows a card with driver Transport Manager and "Children 1 of 32".', 'code'),
 ('0. Setup first', 2, 'ramesh / M2FG-YRAK-9MEA', 'Transport Manager > Student allocation',
  'Child = Aditya Sharma (ADM0011). Route = HANUMAKONDA. Stop = PUBLIC GARDEN. Press Allocate.',
  'A yellow notice first: "This child is on Route 1 - Kompally to school..." and the button becomes "Move this child". Press it.',
  '9840000011 / 9840000011', 'My Child’s Bus',
  'Aditya now shows route HANUMAKONDA, stop PUBLIC GARDEN (it was Route 1 before).', 'code'),
 ('0. Setup first', 3, 'ramesh / M2FG-YRAK-9MEA', 'Transport Manager > Driver Phone Tracker',
  'TS09 UB 4412 shows 1 paired handset. Press Revoke on it.',
  'Paired count goes to 0.',
  'same login', 'Driver Phone Tracker',
  '"0 of 1 vehicle" paired - ready to test pairing from scratch.', 'code'),

 # ---------------------------------------------------------------- payroll
 ('A. Salary month', 1, 'ramesh / M2FG-YRAK-9MEA', 'Institution Admin > Staff attendance register',
  'Pick July 2026. Find Priya Rao. Change one day from Present to Absent.',
  'The day saves as absent.',
  'same login', 'HR & Payroll workspace > Payroll > July 2026',
  'Priya Rao’s LOP column moves off 0 (how far depends on the policy in step 2). NOT a HOD or teacher job - their "Take attendance" is the children and never touches pay.', 'code'),
 ('A. Salary month', 2, 'ramesh / M2FG-YRAK-9MEA', 'Institution Admin > Leave rules & LOP',
  'Change "Half day fraction" from 0.5 to 1.0 (or set max LOP days per month to 1).',
  'The policy saves.',
  'same login', 'HR & Payroll > Payroll > Run payroll, July 2026',
  'The SAME attendance now produces a different LOP figure. Change it back afterwards.', 'code'),
 ('A. Salary month', 3, 'driver@jsm.test / Onrolonrol@ai', 'My profile > Leave',
  'Apply for leave: any 1 day, type = unpaid.',
  'The request is listed as pending.',
  'ramesh / M2FG-YRAK-9MEA', 'HR & Payroll > Leave',
  'The request from Transport Manager (DRV-002) is waiting. Approve it, then check Payroll: an unpaid day becomes LOP if the policy says so.', 'check'),
 ('A. Salary month', 4, 'ramesh / M2FG-YRAK-9MEA', 'HR & Payroll > Payroll',
  'Set month = July, year = 2026. Press Run payroll.',
  'It REFUSES if any staff have no attendance, saying how many. Otherwise 9 payslips appear: Gross ₹3,51,900, Deductions ₹16,200, Net ₹3,35,700.',
  'same login', 'the payslip table',
  '9 rows, T-000 to T-008. riya is tagged "left".', 'code'),
 ('A. Salary month', 5, 'ramesh / M2FG-YRAK-9MEA', 'HR & Payroll > Payroll (July 2026)',
  'Press "Lock payroll & send to finance".',
  'The card title changes to "Locked, ready for the bank".',
  'ramesh, switch to Accounts & Finance', 'Approve & pay salaries > Release the money',
  'THE HANDOVER: the bank file can now be drawn. Before the lock it could not.', 'code'),
 ('A. Salary month', 6, 'ramesh, Accounts & Finance', 'Approve & pay salaries (The payroll run tab)',
  'Press "Download bank file".',
  'A file downloads. NOBODY HAS BEEN PAID - the file existing is not a payment.',
  'same login', 'the downloaded file',
  'The net figures match ₹3,35,700 in total.', 'code'),
 ('A. Salary month', 7, 'ramesh, Accounts & Finance', 'Approve & pay salaries',
  'Press "Mark as paid".',
  'The card title becomes "Paid" and a "Publish payslips" button appears.',
  'same login', 'the same card',
  'Publish payslips is now offered.', 'code'),
 ('A. Salary month', 8, 'ramesh / M2FG-YRAK-9MEA', 'HR & Payroll > Payroll',
  'Press "Publish payslips".',
  'Title becomes "Published" with the line "Every member of staff has been told, in the app and by email."',
  'driver@jsm.test / Onrolonrol@ai', 'the bell, then My profile > My pay',
  'A NEW NOTIFICATION about the payslip, and July 2026 listed under My pay. This is the step staff actually feel.', 'code'),
 ('A. Salary month', 9, 'ramesh / M2FG-YRAK-9MEA', 'HR & Payroll > Payroll',
  'Press "Unlock".',
  'Back to draft.',
  'ramesh, Accounts & Finance', 'Approve & pay salaries > Release the money',
  'The bank file is refused again - proves the gate works both ways. Re-lock when done.', 'code'),

 # ------------------------------------------------------------------- fees
 ('B. Fees', 1, 'ramesh, Accounts & Finance', 'Class & transport fee setup > Fee structure',
  'Open Grade 6. Change one head, e.g. Tuition, from its amount to that amount + ₹100. Save.',
  'The structure saves.',
  'same login', 'the same screen',
  'The new amount. Nothing is charged to anybody yet - a structure is not a demand.', 'check'),
 ('B. Fees', 2, 'ramesh, Accounts & Finance', 'Class & transport fee setup > Raise the demand',
  'Raise the demand for Grade 6 B.',
  'Invoices are created per child.',
  '9840000011 / 9840000011', 'Fees & payments',
  'Aditya Sharma now shows an amount due that includes your ₹100.', 'check'),
 ('B. Fees', 3, 'ramesh, Accounts & Finance', 'Take fee payment',
  'Find Sara Rao (ADM0028), invoice INV/2026-27/00028, ₹11,833.38 due. Take ₹1 in cash.',
  'A receipt number is produced, e.g. RCPT/2026-27/000xx.',
  'ramesh, Accounts & Finance', 'Daybook & cashbook (today)',
  'The ₹1 appears in today’s cash. Also: Fee defaulters on the dashboard drops the outstanding by ₹1.', 'code'),
 ('B. Fees', 4, '9840000011 / 9840000011', 'Fees & payments > Receipts',
  'Press Download on the newest receipt.',
  'A PDF saves (it must NOT open a print dialogue).',
  'same login', 'the saved PDF',
  'School letterhead, the child’s name, the amount, "computer-generated receipt".', 'code'),
 ('B. Fees', 5, 'ramesh, Accounts & Finance', 'Take fee payment',
  'Take ₹1 by CHEQUE from Sara Rao, then mark that payment bounced.',
  'The payment is marked not cleared.',
  'ramesh, Accounts & Finance', 'Who has not paid',
  'Sara Rao is back on the list, and her receipt PDF is watermarked with the status.', 'code'),

 # -------------------------------------------------------------- transport
 ('C. Transport', 1, 'driver@jsm.test / Onrolonrol@ai', 'Vehicles',
  'Open TS09 UB 4412. Change Insurance expiry to a date 10 days from today. Save.',
  'The bus saves.',
  'same login', 'Transport desk (house icon)',
  'A new line: "TS09 UB 4412 - insurance expires in 10 days".', 'code'),
 ('C. Transport', 2, 'driver@jsm.test / Onrolonrol@ai', 'Drivers & attendants',
  'Try to assign driver DRV-002 (Transport Manager) to a SECOND active bus.',
  'IT MUST REFUSE, naming TS09 UB 4412.',
  'same login', 'the error message',
  'The message names the bus he is already on - the phone could not tell which bus it was signing into.', 'code'),
 ('C. Transport', 3, 'driver@jsm.test / Onrolonrol@ai', 'Routes & stops',
  'On HANUMAKONDA, change the fare on stop PUBLIC GARDEN from its value to ₹1,500. Save.',
  'The stop saves.',
  'same login', 'Student allocation',
  'Pick any child + HANUMAKONDA + PUBLIC GARDEN: "Fare this implies" reads ₹1,500.', 'code'),
 ('C. Transport', 4, 'driver@jsm.test / Onrolonrol@ai', 'Vehicles',
  'Change the capacity of TS09 UB 4412 from 32 to 2. Save. Then allocate a 3rd child to HANUMAKONDA.',
  'A warning: "TS09 UB 4412 seats 2, and this makes 3."',
  'same login', 'press Allocate again',
  'IT STILL SAVES. It warns, it does not block. Set capacity back to 32.', 'code'),
 ('C. Transport', 5, 'driver@jsm.test / Onrolonrol@ai', 'Driver Phone Tracker',
  'Select TS09 UB 4412, press Generate code. Note the 6 characters.',
  'A code with an expiry.',
  'a phone', 'erp.xulo.in/bus-tracker/',
  'Enter the code, sign in as the driver. Back in the office the handset shows "paired, seconds ago".', 'code'),
 ('C. Transport', 6, 'the phone', 'erp.xulo.in/bus-tracker/',
  'Scan or type bus sticker 329620, choose route HANUMAKONDA, direction Morning, press Start run.',
  'The trip opens. If it says "scan the bus you are in", the sticker step was skipped.',
  'driver@jsm.test / Onrolonrol@ai', 'Today’s runs',
  'HANUMAKONDA flips from "Not started" to "Running" with a departure time.', 'code'),
 ('C. Transport', 7, 'the phone', '(trip running)',
  'Leave the phone on and move, or just leave it.',
  'Positions are sent.',
  '9840000011 / 9840000011', 'My Child’s Bus',
  'The bus on a map, metres away, an ETA, and the DRIVER’S PHONE NUMBER (shown only while a trip runs).', 'code'),
 ('C. Transport', 8, 'the phone', '(trip running)',
  'Put the phone in airplane mode for 3 minutes.',
  'Positions stop.',
  '9840000011 / 9840000011', 'My Child’s Bus',
  'It must go "no signal", then "stale". IT MUST NEVER SHOW A FROZEN BUS AS LIVE.', 'code'),
 ('C. Transport', 9, 'driver@jsm.test / Onrolonrol@ai', 'Driver Phone Tracker',
  'Switch "parents may watch" OFF.',
  'The setting saves.',
  '9840000011 / 9840000011', 'My Child’s Bus',
  '"Not published", and NO map at all - the position is stripped on the server, not hidden in the page. Switch it back on.', 'code'),
 ('C. Transport', 10, 'driver@jsm.test / Onrolonrol@ai', 'Safety checks',
  'Bus TS09 UB 4412, route HANUMAKONDA, leg Morning. Tick everything EXCEPT Tyres. Save.',
  '"Cleared" is worked out from the ticks - you do not declare it.',
  'same login', 'Transport desk, and Today’s runs',
  '"TS09 UB 4412 failed its morning check: tyres", and a red "Check failed" badge. THE BUS IS NOT BLOCKED - at 7:02 the children are at the stop.', 'code'),
 ('C. Transport', 11, 'driver@jsm.test / Onrolonrol@ai', 'Route attendance',
  'Morning + HANUMAKONDA. Mark Aditya Sharma = On, leave one child unmarked.',
  'The marks save.',
  'same login', 'Today’s runs',
  'Marked goes up by 1; "Not scanned" still counts the child nobody looked at. A child is never silently dropped.', 'code'),
 ('C. Transport', 12, 'driver@jsm.test / Onrolonrol@ai', 'Delays & exceptions',
  'Log a Breakdown on TS09 UB 4412 with any note.',
  'An open incident.',
  'same login', 'Transport desk',
  '"1 incident still open", and the route card carries a "1 open" badge. Resolve it and both clear.', 'code'),
 ('C. Transport', 13, 'driver@jsm.test / Onrolonrol@ai', 'Messages > Parents',
  'Open the Parents tab.',
  'Only families with a child on a bus TODAY are listed.',
  'ramesh', 'Transport Manager > Student allocation',
  'Remove Aditya’s allocation, reload Messages: the Sharma family is GONE from the list the same day.', 'code'),

 # ------------------------------------------------------------- attendance
 ('D. Attendance', 1, 'ramesh / M2FG-YRAK-9MEA', 'Faculty workspace > Take attendance',
  'Grade 6 B, today. Mark Aditya Sharma ABSENT. Save.',
  'The mark saves.',
  '9840000011 / 9840000011', 'Attendance',
  'Today shows as absent for Aditya.', 'check'),
 ('D. Attendance', 2, 'ramesh / M2FG-YRAK-9MEA', 'Institution Admin > Attendance overview',
  'Look at today.',
  'Sections with no attendance marked are listed.',
  'same login', 'the same screen',
  'Grade 6 B is NOT listed (you just marked it). This chases the teacher, not the child.', 'check'),

 # ----------------------------------------------------------- notifications
 ('E. Notifications', 1, 'ramesh / M2FG-YRAK-9MEA', 'Faculty workspace > Class Status',
  'Post a status to Grade 6 B with any text.',
  'The post appears on the class wall.',
  '9840000011 / 9840000011', 'the bell, then the feed',
  'A notification, and the post. Check the audience line is NOT shown to the parent.', 'code'),
 ('E. Notifications', 2, '9840000011 / 9840000011', 'Concerns',
  'Raise a concern, category = Transport, any text.',
  'It is submitted.',
  'ramesh / M2FG-YRAK-9MEA', 'Grievances',
  'The concern is listed and routed. Answer it; the parent sees the reply and can reopen.', 'code'),
 ('E. Notifications', 3, 'ramesh / M2FG-YRAK-9MEA', 'Faculty workspace > Homework',
  'Set homework for Grade 6 B due tomorrow.',
  'It saves.',
  '9840000011 / 9840000011', 'the bell, then Homework',
  'The homework is listed with its due date.', 'check'),
 ('E. Notifications', 4, '9840000011 / 9840000011', 'Communication',
  'Write a message to one of Aditya’s teachers.',
  'The thread opens. Only staff who TEACH Aditya can be chosen.',
  'ramesh / M2FG-YRAK-9MEA', 'Faculty workspace > Messages > Parents',
  'The message, under Aditya Sharma.', 'code'),

 # ------------------------------------------------------------------ exams
 ('F. Exams', 1, 'ramesh / M2FG-YRAK-9MEA', 'Examinations > Hall ticket issue',
  'Choose an exam, press Allocate seats.',
  'Every candidate gets a hall, row and seat. Re-running REPLACES the whole allocation.',
  'same login', 'the Seating plan card, then Print',
  'Neighbours come from different sections on purpose. The print is headed "Seating plan" on the school letterhead, in Inter.', 'code'),
 ('F. Exams', 2, 'ramesh / M2FG-YRAK-9MEA', 'Faculty workspace > Marks entry',
  'Enter a mark for Aditya Sharma in any paper. Save.',
  'The mark saves.',
  'ramesh', 'Mark moderation (HOD or Institution Admin - NOT the exam controller)',
  'The mark is waiting to be approved.', 'check'),
 ('F. Exams', 3, 'ramesh / M2FG-YRAK-9MEA', 'Report cards',
  'Publish the report card for Grade 6 B.',
  'Released.',
  '9840000011 / 9840000011', 'Results & report cards',
  'Aditya’s result is visible. This is the most public single action in the product.', 'check'),

 # ----------------------------------------------------------- certificates
 ('G. Certificates', 1, '9840000011 / 9840000011', 'Certificate requests',
  'Request a Bonafide certificate for Aditya.',
  'The request is submitted.',
  'ramesh / M2FG-YRAK-9MEA', 'Certificates & transfers',
  'The request is listed.', 'code'),
 ('G. Certificates', 2, 'ramesh / M2FG-YRAK-9MEA', 'Certificates & transfers',
  'Issue it, preview, then print.',
  'The certificate is produced on the school design.',
  'same login', 'the printed page',
  'A Bonafide does NOT carry fees outstanding or attendance; a Transfer Certificate DOES. Check that difference.', 'code'),
]

FLOW_NOTE = {
 '0. Setup first': 'Do these three before anything else or half the transport chain has nothing to act on.',
 'A. Salary month': 'Attendance becomes money. A wrong tick in week one is a wrong bank file in week five.',
 'B. Fees': 'Money in: structure, demand, counter, receipt, day book.',
 'C. Transport': 'One allocation row is a fee, a register line, a parent map and a messaging right. Test it hardest.',
 'D. Attendance': 'The daily mark, and who chases whom when it is missing.',
 'E. Notifications': 'The bells. Do the thing in one account, then open the other and look.',
 'F. Exams': 'Ends at publishing a result, which every family sees.',
 'G. Certificates': 'A parent asks, the office issues, and the paper carries different things by kind.',
}

LOGINS = [(role, who + '  /  ' + pw, note) for role, who, pw, note in CAST]
