-- GENERATED by scripts/schema-sync.mjs from migrations/control/ (through 0012_housekeeping_indexes).
-- Do not edit: write a migration (npm run migrate -- new control <name>), then npm run schema:sync.
-- A fresh CONTROL database.
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS _migrations (
  scope TEXT NOT NULL,
  version INTEGER NOT NULL,
  name TEXT NOT NULL,
  checksum TEXT NOT NULL,
  applied_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  PRIMARY KEY (scope, version)
);

CREATE TABLE IF NOT EXISTS institutions (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  short_name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE COLLATE NOCASE,
  status TEXT NOT NULL DEFAULT 'active',
  timezone TEXT NOT NULL DEFAULT 'Asia/Kolkata',
  locale TEXT NOT NULL DEFAULT 'en-IN',
  primary_color TEXT NOT NULL DEFAULT '#1e40af',
  logo_key TEXT,
  teacher_day_code_secret BLOB,
  -- The school's own D1 database, and the Worker binding that reaches it.
  d1_database_id TEXT NOT NULL,
  d1_binding TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
, country TEXT NOT NULL DEFAULT 'in', accent_color TEXT, tagline TEXT, login_headline TEXT, login_message TEXT, support_email TEXT, support_phone TEXT, custom_domain TEXT, app_id TEXT);

CREATE TABLE IF NOT EXISTS plans (
  code TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  price_paise INTEGER NOT NULL DEFAULT 0,
  price_monthly_paise INTEGER,
  max_students INTEGER,
  max_campuses INTEGER,
  max_storage_gb INTEGER,
  modules TEXT NOT NULL DEFAULT '{}',
  sequence INTEGER NOT NULL DEFAULT 0,
  custom_integration INTEGER NOT NULL DEFAULT 0,
  retired_at TEXT
);

CREATE TABLE IF NOT EXISTS subscriptions (
  institution_id TEXT PRIMARY KEY REFERENCES institutions(id) ON DELETE CASCADE,
  plan_code TEXT NOT NULL REFERENCES plans(code),
  status TEXT NOT NULL DEFAULT 'trial',
  started_on TEXT NOT NULL,
  renews_on TEXT,
  trial_ends_on TEXT,
  licensed_students INTEGER,
  agreed_price_paise INTEGER,
  storage_gb INTEGER,
  notes TEXT,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_users (
  id TEXT PRIMARY KEY,
  email TEXT UNIQUE COLLATE NOCASE,
  username TEXT UNIQUE COLLATE NOCASE,
  phone TEXT UNIQUE,
  full_name TEXT NOT NULL,
  password_hash TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS login_index (
  kind TEXT NOT NULL CHECK (kind IN ('email','phone','username')),
  value TEXT NOT NULL COLLATE NOCASE,
  institution_id TEXT REFERENCES institutions(id) ON DELETE CASCADE,  -- NULL = platform user
  user_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (kind, value, institution_id, user_id)
);
CREATE INDEX IF NOT EXISTS login_index_value ON login_index(value);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  token_hash TEXT NOT NULL UNIQUE,          -- hex sha256 of the cookie value
  institution_id TEXT REFERENCES institutions(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  ip TEXT,
  user_agent TEXT,
  via TEXT NOT NULL DEFAULT 'password',
  created_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  revoked_at TEXT,
  ended_reason TEXT
);
CREATE INDEX IF NOT EXISTS sessions_user ON sessions(user_id);

CREATE TABLE IF NOT EXISTS login_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  at TEXT NOT NULL,
  identifier TEXT,
  outcome TEXT NOT NULL,
  institution_id TEXT,
  user_id TEXT,
  ip TEXT,
  user_agent TEXT
);

CREATE TABLE IF NOT EXISTS login_throttle (
  key TEXT PRIMARY KEY,
  failures INTEGER NOT NULL DEFAULT 0,
  window_started_at TEXT NOT NULL,
  locked_until TEXT
);

CREATE TABLE IF NOT EXISTS platform_user_roles (
  user_id TEXT NOT NULL REFERENCES platform_users(id) ON DELETE CASCADE,
  role_key TEXT NOT NULL,   -- 'super_admin' | 'seller_admin' | 'support_admin'
  created_at TEXT NOT NULL,
  PRIMARY KEY (user_id, role_key)
);

CREATE TABLE IF NOT EXISTS purchase_enquiries (
  id TEXT PRIMARY KEY, school_name TEXT NOT NULL, contact_name TEXT NOT NULL,
  email TEXT COLLATE NOCASE, phone TEXT, district TEXT, state TEXT, board TEXT, students INTEGER,
  plan_code TEXT REFERENCES plans(code) ON DELETE SET NULL, message TEXT,
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new','contacted','demo_booked','won','lost')),
  provisioned_institution_id TEXT REFERENCES institutions(id) ON DELETE SET NULL,
  source TEXT NOT NULL DEFAULT 'website',
  owner_user_id TEXT REFERENCES platform_users(id) ON DELETE SET NULL,
  next_follow_up TEXT, lost_reason TEXT, value_paise INTEGER,
  created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
  CHECK (email IS NOT NULL OR phone IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS purchase_enquiries_open ON purchase_enquiries(created_at DESC) WHERE status IN ('new','contacted','demo_booked');

CREATE TABLE IF NOT EXISTS purchase_enquiry_notes (
  id TEXT PRIMARY KEY, enquiry_id TEXT NOT NULL REFERENCES purchase_enquiries(id) ON DELETE CASCADE,
  kind TEXT NOT NULL DEFAULT 'note' CHECK (kind IN ('note','stage','call','email','meeting')),
  body TEXT NOT NULL, author_id TEXT REFERENCES platform_users(id) ON DELETE SET NULL, created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_events (
  id TEXT PRIMARY KEY, kind TEXT NOT NULL, ok INTEGER NOT NULL DEFAULT 1,
  institution_id TEXT REFERENCES institutions(id) ON DELETE SET NULL,
  subject TEXT NOT NULL DEFAULT '', detail TEXT NOT NULL DEFAULT '',
  actor_id TEXT REFERENCES platform_users(id) ON DELETE SET NULL, at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS platform_events_at ON platform_events(at);

CREATE TABLE IF NOT EXISTS platform_costs (
  id INTEGER PRIMARY KEY CHECK (id = 1), infra_paise INTEGER NOT NULL DEFAULT 0,
  storage_paise_per_gb INTEGER NOT NULL DEFAULT 0, sms_paise INTEGER NOT NULL DEFAULT 0,
  email_paise INTEGER NOT NULL DEFAULT 0, whatsapp_paise INTEGER NOT NULL DEFAULT 0,
  notes TEXT NOT NULL DEFAULT '', updated_by TEXT REFERENCES platform_users(id) ON DELETE SET NULL, updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_broadcasts (
  id TEXT PRIMARY KEY, severity TEXT NOT NULL DEFAULT 'info' CHECK (severity IN ('info','warning','critical')),
  title TEXT NOT NULL, body TEXT NOT NULL DEFAULT '', starts_at TEXT NOT NULL, ends_at TEXT,
  created_by TEXT REFERENCES platform_users(id) ON DELETE SET NULL, created_at TEXT NOT NULL, retired_at TEXT,
  CHECK (ends_at IS NULL OR ends_at > starts_at)
);

CREATE TABLE IF NOT EXISTS password_resets (
  id TEXT PRIMARY KEY,
  institution_id TEXT REFERENCES institutions(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  requested_ip TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS password_resets_user ON password_resets(user_id, created_at);
CREATE INDEX IF NOT EXISTS password_resets_expiry ON password_resets(expires_at) WHERE used_at IS NULL;

CREATE TABLE IF NOT EXISTS signup_orders (
  id TEXT PRIMARY KEY,
  school_name TEXT NOT NULL,
  contact_name TEXT NOT NULL,
  email TEXT NOT NULL COLLATE NOCASE,
  phone TEXT, district TEXT, state TEXT, board TEXT, students INTEGER,
  admin_username TEXT COLLATE NOCASE,
  plan_code TEXT NOT NULL REFERENCES plans(code) ON DELETE RESTRICT,
  amount_paise INTEGER NOT NULL,
  order_ref TEXT NOT NULL UNIQUE,
  payment_ref TEXT, signature TEXT,
  status TEXT NOT NULL DEFAULT 'created',
  failure_reason TEXT,
  institution_id TEXT REFERENCES institutions(id) ON DELETE SET NULL,
  admin_user_id TEXT,
  credentials_sent_at TEXT,
  billing_period TEXT NOT NULL DEFAULT 'yearly',
  created_at TEXT NOT NULL, paid_at TEXT, updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS signup_orders_status ON signup_orders(status);

CREATE TABLE IF NOT EXISTS jobs (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  queue TEXT NOT NULL DEFAULT 'default',
  institution_id TEXT,
  state TEXT NOT NULL DEFAULT 'pending',
  attempts INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 6,
  last_error TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  finished_at TEXT
);
CREATE INDEX IF NOT EXISTS jobs_queue_state ON jobs(queue, state);
CREATE INDEX IF NOT EXISTS jobs_created ON jobs(created_at);

CREATE TABLE IF NOT EXISTS cron_runs (
  name TEXT PRIMARY KEY,
  last_run_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS institutions_custom_domain ON institutions (custom_domain COLLATE NOCASE) WHERE custom_domain IS NOT NULL;

CREATE TABLE IF NOT EXISTS school_groups (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE COLLATE NOCASE,
  created_by TEXT REFERENCES platform_users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS school_group_members (
  institution_id TEXT PRIMARY KEY REFERENCES institutions(id) ON DELETE CASCADE,
  group_id TEXT NOT NULL REFERENCES school_groups(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS school_group_members_group ON school_group_members(group_id);

CREATE TABLE IF NOT EXISTS school_group_admins (
  group_id TEXT NOT NULL REFERENCES school_groups(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  home_institution_id TEXT NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  PRIMARY KEY (group_id, user_id)
);
CREATE INDEX IF NOT EXISTS school_group_admins_user ON school_group_admins(user_id);

CREATE TABLE IF NOT EXISTS board_memberships (
  user_id TEXT NOT NULL,
  institution_id TEXT NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,
  home_institution_id TEXT NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,
  via_group TEXT REFERENCES school_groups(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (user_id, institution_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS institutions_app_id ON institutions (app_id) WHERE app_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS school_errors (
  institution_id TEXT NOT NULL,
  hour TEXT NOT NULL,                 -- 'YYYY-MM-DDTHH'
  count INTEGER NOT NULL DEFAULT 0,
  last_path TEXT,
  last_at TEXT NOT NULL,
  PRIMARY KEY (institution_id, hour)
);

CREATE TABLE IF NOT EXISTS school_health (
  institution_id TEXT PRIMARY KEY REFERENCES institutions(id) ON DELETE CASCADE,
  data TEXT NOT NULL,
  computed_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS usage_alerts (
  institution_id TEXT NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,
  metric TEXT NOT NULL,
  level INTEGER NOT NULL,
  used REAL NOT NULL,
  lim REAL NOT NULL,
  pct INTEGER NOT NULL,
  message TEXT NOT NULL,
  notified_level INTEGER NOT NULL DEFAULT 0,
  raised_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (institution_id, metric)
);
CREATE INDEX IF NOT EXISTS sessions_institution ON sessions(institution_id, last_seen_at);
CREATE INDEX IF NOT EXISTS jobs_institution ON jobs(institution_id, state);

CREATE TABLE IF NOT EXISTS school_feature_overrides (
  institution_id TEXT NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,
  feature_id TEXT NOT NULL,
  enabled INTEGER NOT NULL,
  ends_at TEXT,
  note TEXT NOT NULL DEFAULT '',
  set_by TEXT REFERENCES platform_users(id) ON DELETE SET NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (institution_id, feature_id)
);
CREATE INDEX IF NOT EXISTS school_feature_overrides_feature ON school_feature_overrides(feature_id);

CREATE TABLE IF NOT EXISTS platform_broadcast_targets (
  broadcast_id TEXT PRIMARY KEY REFERENCES platform_broadcasts(id) ON DELETE CASCADE,
  target_kind TEXT NOT NULL DEFAULT 'all' CHECK (target_kind IN ('all','group','plan','schools')),
  target_ids TEXT NOT NULL DEFAULT '[]',
  audiences TEXT NOT NULL DEFAULT '["admins","staff","parents"]',
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_broadcast_reads (
  broadcast_id TEXT NOT NULL REFERENCES platform_broadcasts(id) ON DELETE CASCADE,
  institution_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  seen_at TEXT NOT NULL,
  dismissed_at TEXT,
  PRIMARY KEY (broadcast_id, institution_id, user_id)
);
CREATE INDEX IF NOT EXISTS platform_broadcast_reads_school ON platform_broadcast_reads(broadcast_id, institution_id);

CREATE TABLE IF NOT EXISTS provisioning (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE COLLATE NOCASE,
  country TEXT NOT NULL DEFAULT 'in',
  name TEXT NOT NULL,
  short_name TEXT NOT NULL,
  plan_code TEXT,
  trial_days INTEGER NOT NULL DEFAULT 30,
  district TEXT,
  state TEXT,
  affiliation_board TEXT,
  admin_name TEXT NOT NULL,
  admin_email TEXT,
  admin_phone TEXT,
  admin_username TEXT,
  -- Only the hash: the one-time password is returned once, to the seller who asked.
  admin_password_hash TEXT NOT NULL,
  -- {primary_color, accent_color, tagline, support_email, support_phone}
  branding TEXT NOT NULL DEFAULT '{}',
  institution_id TEXT NOT NULL,
  admin_user_id TEXT NOT NULL,
  db_name TEXT NOT NULL,
  d1_database_id TEXT,
  d1_binding TEXT NOT NULL,
  -- 1 once this row's job created the database, so only then may a discard delete it.
  db_created INTEGER NOT NULL DEFAULT 0,
  -- queued | creating_database | applying_schema | seeding | attaching | ready | failed
  stage TEXT NOT NULL DEFAULT 'queued',
  failed_stage TEXT,
  error TEXT,
  schema_done INTEGER NOT NULL DEFAULT 0,
  schema_total INTEGER NOT NULL DEFAULT 0,
  attempts INTEGER NOT NULL DEFAULT 0,
  job_id TEXT,
  created_by TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  finished_at TEXT
);
CREATE INDEX IF NOT EXISTS provisioning_created ON provisioning(created_at);

CREATE TABLE IF NOT EXISTS backups (
  id TEXT PRIMARY KEY,
  institution_id TEXT,
  scope TEXT NOT NULL DEFAULT 'school',        -- school | control
  kind TEXT NOT NULL DEFAULT 'nightly',        -- nightly | manual
  backup_date TEXT NOT NULL,                   -- YYYY-MM-DD (UTC)
  object_key TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'running',      -- running | succeeded | failed | pruned | replaced
  tables INTEGER NOT NULL DEFAULT 0,
  row_count INTEGER NOT NULL DEFAULT 0,
  size_bytes INTEGER NOT NULL DEFAULT 0,
  sha256 TEXT,
  error TEXT,
  requested_by TEXT,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  pruned_at TEXT
);
CREATE INDEX IF NOT EXISTS backups_school ON backups (institution_id, started_at);
CREATE INDEX IF NOT EXISTS backups_key ON backups (object_key);

CREATE TABLE IF NOT EXISTS restores (
  id TEXT PRIMARY KEY,
  institution_id TEXT NOT NULL,
  d1_database_id TEXT NOT NULL,
  target_timestamp TEXT,
  target_bookmark TEXT,
  pre_bookmark TEXT,
  result_bookmark TEXT,
  undoes_restore_id TEXT,
  status TEXT NOT NULL,                        -- dry_run | succeeded | failed
  error TEXT,
  reason TEXT,
  actor_id TEXT NOT NULL,
  actor_name TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS restores_school ON restores (institution_id, created_at);

CREATE TABLE IF NOT EXISTS school_exports (
  id TEXT PRIMARY KEY,
  institution_id TEXT NOT NULL,
  purpose TEXT NOT NULL DEFAULT 'request',     -- request | offboarding
  status TEXT NOT NULL DEFAULT 'queued',       -- queued | running | ready | failed | expired
  object_key TEXT,
  size_bytes INTEGER NOT NULL DEFAULT 0,
  tables INTEGER NOT NULL DEFAULT 0,
  row_count INTEGER NOT NULL DEFAULT 0,
  files INTEGER NOT NULL DEFAULT 0,
  error TEXT,
  requested_by TEXT,
  requested_by_name TEXT,
  requested_by_platform INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  finished_at TEXT,
  expires_at TEXT
);
CREATE INDEX IF NOT EXISTS school_exports_school ON school_exports (institution_id, created_at);

CREATE TABLE IF NOT EXISTS school_lifecycle (
  institution_id TEXT PRIMARY KEY,
  state TEXT NOT NULL DEFAULT 'active',
  read_only_days INTEGER NOT NULL DEFAULT 30,
  leaving_at TEXT,
  export_id TEXT,
  read_only_at TEXT,
  read_only_until TEXT,
  archived_at TEXT,
  prior_status TEXT,
  delete_requested_at TEXT,
  delete_requested_by TEXT,
  deleted_at TEXT,
  note TEXT,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS school_lifecycle_events (
  id TEXT PRIMARY KEY,
  institution_id TEXT NOT NULL,
  step TEXT NOT NULL,
  detail TEXT,
  actor_id TEXT,
  actor_name TEXT,
  at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS school_lifecycle_events_school ON school_lifecycle_events (institution_id, at);

CREATE TABLE IF NOT EXISTS seller_audit (
  id TEXT PRIMARY KEY,
  at TEXT NOT NULL,
  actor_id TEXT NOT NULL,
  actor_name TEXT,
  actor_roles TEXT,
  acting_as INTEGER NOT NULL DEFAULT 0,        -- 1 when done inside a school (X-Acting-Institution)
  method TEXT NOT NULL,
  path TEXT NOT NULL,
  route TEXT,
  action TEXT NOT NULL,
  institution_id TEXT,
  institution_name TEXT,
  target TEXT,
  before_summary TEXT,
  after_summary TEXT,
  status INTEGER,
  ip TEXT
);
CREATE INDEX IF NOT EXISTS seller_audit_at ON seller_audit (at);
CREATE INDEX IF NOT EXISTS seller_audit_school ON seller_audit (institution_id, at);
CREATE INDEX IF NOT EXISTS seller_audit_actor ON seller_audit (actor_id, at);
CREATE TRIGGER IF NOT EXISTS seller_audit_no_update BEFORE UPDATE ON seller_audit
BEGIN SELECT RAISE(ABORT, 'seller_audit is append-only'); END;
CREATE TRIGGER IF NOT EXISTS seller_audit_no_delete BEFORE DELETE ON seller_audit
BEGIN SELECT RAISE(ABORT, 'seller_audit is append-only'); END;

CREATE TABLE IF NOT EXISTS billing_settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  seller_name TEXT NOT NULL DEFAULT '',
  seller_address TEXT NOT NULL DEFAULT '',
  seller_gstin TEXT NOT NULL DEFAULT '',
  seller_email TEXT NOT NULL DEFAULT '',
  bank_details TEXT NOT NULL DEFAULT '',
  upi_vpa TEXT NOT NULL DEFAULT '',
  invoice_prefix TEXT NOT NULL DEFAULT 'INV',
  gst_rate_bp INTEGER NOT NULL DEFAULT 1800,          -- basis points: 1800 = 18%
  due_days INTEGER NOT NULL DEFAULT 15,               -- issued_on + due_days = due_on
  grace_days INTEGER NOT NULL DEFAULT 15,             -- past_due after due_on + grace_days
  suspend_after_days INTEGER NOT NULL DEFAULT 30,     -- suspended after a further this many days
  updated_by TEXT REFERENCES platform_users(id) ON DELETE SET NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS billing_invoices (
  id TEXT PRIMARY KEY,
  institution_id TEXT NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,
  number TEXT NOT NULL UNIQUE,
  fy TEXT NOT NULL,
  seq INTEGER NOT NULL,
  issued_on TEXT NOT NULL,
  due_on TEXT NOT NULL,
  period_from TEXT,
  period_to TEXT,
  plan_code TEXT,
  billing_period TEXT NOT NULL DEFAULT 'yearly',
  description TEXT NOT NULL,
  school_gstin TEXT,
  amount_paise INTEGER NOT NULL,                      -- taxable value
  gst_rate_bp INTEGER NOT NULL,
  gst_paise INTEGER NOT NULL,
  total_paise INTEGER NOT NULL,
  paid_paise INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'issued' CHECK (status IN ('issued','partial','paid','void')),
  seller_gstin TEXT NOT NULL DEFAULT '',
  notes TEXT,
  created_by TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (fy, seq)
);
CREATE INDEX IF NOT EXISTS billing_invoices_school ON billing_invoices(institution_id, issued_on);
CREATE INDEX IF NOT EXISTS billing_invoices_open ON billing_invoices(due_on) WHERE status IN ('issued','partial');

CREATE TABLE IF NOT EXISTS billing_payments (
  id TEXT PRIMARY KEY,
  invoice_id TEXT NOT NULL REFERENCES billing_invoices(id) ON DELETE CASCADE,
  institution_id TEXT NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,
  amount_paise INTEGER NOT NULL CHECK (amount_paise > 0),
  method TEXT NOT NULL CHECK (method IN ('upi','neft','cheque','cash','online')),
  reference TEXT,
  paid_on TEXT NOT NULL,
  gateway_order_ref TEXT UNIQUE,
  recorded_by TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS billing_payments_invoice ON billing_payments(invoice_id);

CREATE TABLE IF NOT EXISTS billing_gateway_orders (
  order_ref TEXT PRIMARY KEY,
  invoice_id TEXT NOT NULL REFERENCES billing_invoices(id) ON DELETE CASCADE,
  institution_id TEXT NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,
  amount_paise INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'created' CHECK (status IN ('created','paid','failed')),
  payment_ref TEXT,
  failure_reason TEXT,
  created_by TEXT,
  created_at TEXT NOT NULL,
  paid_at TEXT
);

CREATE TABLE IF NOT EXISTS billing_reminders (
  institution_id TEXT NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,
  renews_on TEXT NOT NULL,
  days_before INTEGER NOT NULL,
  recipient TEXT,
  sent_at TEXT NOT NULL,
  PRIMARY KEY (institution_id, renews_on, days_before)
);

CREATE TABLE IF NOT EXISTS billing_status_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  institution_id TEXT NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,
  from_status TEXT, to_status TEXT NOT NULL, reason TEXT NOT NULL, at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS onboarding_progress (
  institution_id TEXT PRIMARY KEY REFERENCES institutions(id) ON DELETE CASCADE,
  admin_signed_in_at TEXT,
  profile_complete_at TEXT,
  classes_set_up_at TEXT,
  students_imported_at TEXT,
  staff_added_at TEXT,
  first_attendance_at TEXT,
  first_fee_at TEXT,
  first_parent_signed_in_at TEXT,
  scan_error TEXT,
  checked_at TEXT NOT NULL,
  last_nudged_at TEXT,
  nudge_count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS dead_letters (
  id TEXT NOT NULL PRIMARY KEY,
  job_id TEXT,
  type TEXT NOT NULL,
  institution_id TEXT,
  payload TEXT,
  error TEXT,
  attempts INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  alerted_at TEXT,
  resolved_at TEXT
);
CREATE INDEX IF NOT EXISTS dead_letters_recent ON dead_letters (created_at);
CREATE INDEX IF NOT EXISTS dead_letters_by_type ON dead_letters (type, created_at);
CREATE INDEX IF NOT EXISTS sessions_expires ON sessions (expires_at);
CREATE INDEX IF NOT EXISTS sessions_created ON sessions (created_at);
CREATE INDEX IF NOT EXISTS login_events_at ON login_events (at);
CREATE INDEX IF NOT EXISTS login_events_user_at ON login_events (user_id, at);
CREATE INDEX IF NOT EXISTS login_throttle_window ON login_throttle (window_started_at);
CREATE INDEX IF NOT EXISTS jobs_finished ON jobs (finished_at) WHERE finished_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS login_index_institution ON login_index (institution_id);

CREATE TABLE IF NOT EXISTS cache_versions (scope TEXT PRIMARY KEY, version INTEGER NOT NULL DEFAULT 0, updated_at TEXT);

-- Rows the migrations insert (settings singletons) and the migrations applied.
INSERT OR IGNORE INTO _migrations (scope, version, name, checksum) VALUES ('control', 1, 'baseline', '288981cbd05a0798d95d27eae066a9cbe92502cb92584067df07cf35b9629d0b');
INSERT OR IGNORE INTO _migrations (scope, version, name, checksum) VALUES ('control', 2, 'white_label', '102895b65dfb270f0d14304b738781eebee5e53c19361868827b3b46e906e113');
INSERT OR IGNORE INTO _migrations (scope, version, name, checksum) VALUES ('control', 3, 'school_groups', '34f0a04abadb66bf8356bc1e9104e9ece11bb2b3c60e9eea6fcc1eb00ec75366');
INSERT OR IGNORE INTO _migrations (scope, version, name, checksum) VALUES ('control', 4, 'app_id', 'b254163f153fe0c4a816bcecd0542a5ff632936028fc5285db362c90a0507a56');
INSERT OR IGNORE INTO _migrations (scope, version, name, checksum) VALUES ('control', 5, 'health', '55fa9f24a6bd79e9644c826abbad78fd909769d60116d145ef23a99b1d3ce248');
INSERT OR IGNORE INTO _migrations (scope, version, name, checksum) VALUES ('control', 6, 'features', '52d104438be208c91d5c6f97a9145d2ce552ef17505310b16f7cd0005ad8ab5b');
INSERT OR IGNORE INTO _migrations (scope, version, name, checksum) VALUES ('control', 7, 'provisioning', '2b2e2874ead996fc14b94525626ff4d576d47029e602951ab2eed9e2175ba3e0');
INSERT OR IGNORE INTO _migrations (scope, version, name, checksum) VALUES ('control', 8, 'lifecycle', '09f9def075fd247158ef918fe2a1200d2033854a936f26be046317d704fde26e');
INSERT OR IGNORE INTO _migrations (scope, version, name, checksum) VALUES ('control', 9, 'billing', 'f4b5613c506d69191861410eca980b8ea23bacd224523100fb372d0029dee753');
INSERT OR IGNORE INTO _migrations (scope, version, name, checksum) VALUES ('control', 11, 'dead_letters', '2329c5b54cd7adda34edc0eb72dea6d9b222cde2adb5776e2706de58fcb83504');
INSERT OR IGNORE INTO _migrations (scope, version, name, checksum) VALUES ('control', 12, 'housekeeping_indexes', '48fd6ee1f12b198fdaf3f9358c252cc3d7bd9af34d97b3e64ddc11aa23a6a60c');
INSERT OR IGNORE INTO "platform_costs" ("id", "infra_paise", "storage_paise_per_gb", "sms_paise", "email_paise", "whatsapp_paise", "notes", "updated_by", "updated_at") VALUES (1, 0, 0, 0, 0, 0, '', NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO "billing_settings" ("id", "seller_name", "seller_address", "seller_gstin", "seller_email", "bank_details", "upi_vpa", "invoice_prefix", "gst_rate_bp", "due_days", "grace_days", "suspend_after_days", "updated_by", "updated_at") VALUES (1, '', '', '', '', '', '', 'INV', 1800, 15, 15, 30, NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
